http:
  listner:
     host: "localhost"
     port: "9081"
     path: "/FastGocall/{ServiceType}"
     
db:
  oracle:
    host: "0.0.0.0"
    port: "1521"
    user: "system"
    password: "system"
    instance: ""